# Generated by Django 4.2 on 2023-05-03 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myroof", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(max_length=20)),
                ("street", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=50)),
                ("building_number", models.CharField(default="NG", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("GYM", "Gym"),
                            ("KITCHEN", "Kitchen"),
                            ("POOL", "Pool"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("floors", models.IntegerField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="myroof.address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("property_type", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("availability", models.BooleanField(default=True)),
                ("floor", models.IntegerField()),
                ("area", models.FloatField(default=0)),
                (
                    "rooms",
                    models.IntegerField(
                        choices=[
                            (1, "1 room"),
                            (2, "2 rooms"),
                            (3, "3 rooms"),
                            (4, "4 rooms or more"),
                        ]
                    ),
                ),
                (
                    "bathrooms",
                    models.IntegerField(
                        choices=[
                            (1, "1 room"),
                            (2, "2 rooms"),
                            (3, "3 rooms"),
                            (4, "4 rooms or more"),
                        ]
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                ("amenities", models.ManyToManyField(to="myroof.amenity")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myroof.building",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_valid", models.BooleanField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("review", models.JSONField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myroof.property",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                ("date_built", models.DateField()),
                ("website", models.CharField(max_length=50)),
                ("image_url", models.CharField(max_length=200)),
                ("amenities", models.ManyToManyField(to="myroof.amenity")),
                (
                    "constructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="complex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="myroof.complex"
            ),
        ),
    ]
