# Generated by Django 4.2 on 2023-05-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myroof", "0003_alter_userdata_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complex",
            name="image_url",
        ),
        migrations.AddField(
            model_name="complex",
            name="images",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="property",
            name="images",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(max_length=10000),
        ),
    ]
